# Generated by Django 3.2.7 on 2021-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='mark4',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='mark5',
            field=models.IntegerField(default=False),
        ),
    ]
